# Generated by Django 3.2 on 2021-11-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211119_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
